name: 🐛 Bug Report
description: Report an issue or unexpected behavior in the Troubleshooting Wizard
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## 🐛 Bug Report

        Thank you for reporting a bug! Please provide detailed information to help us understand and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Describe the Bug
      description: A clear and concise description of what the bug is.
      placeholder: |
        What did you expect to happen? What actually happened?
        Include any error messages you received.
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What you expected to happen.
      placeholder: Describe what should have happened instead.

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened.
      placeholder: Describe what happened instead of the expected behavior.

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide details about your environment.
      placeholder: |
        - OS: [e.g. Windows 10, macOS 12.1, Ubuntu 20.04]
        - Python version: [e.g. 3.9.0]
        - Troubleshooting Wizard version: [e.g. 1.0.0]
        - Any relevant hardware or system specifications
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
      placeholder: |
        - Screenshots or videos if applicable
        - Log files or error output
        - Related issues or discussions
        - Workarounds you've tried

  - type: textarea
    id: possible-solution
    attributes:
      label: Possible Solution
      description: If you have suggestions on how to fix this, please describe them here.
      placeholder: Optional - Any ideas you have for resolving this issue.

  - type: checkboxes
    id: checklist
    attributes:
      label: Before Submitting
      description: Please check the following before submitting this bug report.
      options:
        - label: I have searched existing issues to make sure this is not a duplicate
          required: true
        - label: I have provided clear steps to reproduce the issue
          required: true
        - label: I have included relevant environment details
          required: true
        - label: I have described the expected vs actual behavior
          required: true
