name: 💬 General Issue
description: For questions, discussions, or issues that don't fit other categories
title: "[General]: "
labels: ["question", "discussion", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## 💬 General Issue

        Use this form for questions, discussions, support requests, or any other issues that don't fit into the Bug Report or Feature Request categories.

  - type: dropdown
    id: issue-type
    attributes:
      label: Issue Type
      description: What type of issue is this?
      options:
        - Question/Support
        - Documentation Issue
        - Installation/Setup Problem
        - Performance Issue
        - Configuration Question
        - Integration Issue
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please describe your issue, question, or topic for discussion.
      placeholder: |
        Provide as much detail as possible.
        For questions, explain what you're trying to achieve.
        For issues, describe what you're experiencing.
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any additional information that might help us understand your issue.
      placeholder: |
        - Your environment (OS, Python version, etc.)
        - What you've already tried
        - Relevant error messages or logs
        - Screenshots if applicable
        - Related issues or discussions

  - type: textarea
    id: expected-outcome
    attributes:
      label: Expected Outcome
      description: What would you like to see happen?
      placeholder: |
        For questions: What information are you looking for?
        For issues: What should happen instead?
        For discussions: What topics would you like to discuss?

  - type: checkboxes
    id: checklist
    attributes:
      label: Before Submitting
      description: Please check the following before submitting.
      options:
        - label: I have searched existing issues to make sure this is not a duplicate
          required: true
        - label: I have provided clear and detailed information
          required: true
        - label: I understand this may be a discussion topic and not require immediate action
          required: false
