name: CI Pipeline

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  test:
    name: Run Tests
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.13
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov
        # Install Tkinter dependencies
        choco install -y python --version 3.13.7
        refreshenv
    
    - name: Run unit tests
      run: |
        python -m pytest tests/ -v -m "not gui" --no-header --tb=short
    
    - name: Run health checks
      run: |
        python -c "from src.logging_config import setup_logging; setup_logging(); from src.health_check import run_health_checks; exit(0 if run_health_checks() else 1)"
    
    - name: Run code quality checks
      run: |
        python tools/format_code.py

  build:
    name: Build Package
    needs: test
    runs-on: windows-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.13
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install build
    
    - name: Build package
      run: |
        python -m build
    
    - name: Build executable
      run: |
        powershell -File tools/build.ps1
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: troubleshooting-wizard-exe
        path: dist/*.exe
        retention-days: 30
